### ISSUE TITLE
Add a notice that "/" route must be listed last

### ISSUE THREAD

**Issue by Papooch** [gh0st-work/solid-js-router#2]
I spent an unnecessary amount of time figuring out why my routes don't work and it turned out, I had the "/" route listed first and it was matching all "/other" "/routes".

Other than that, this library is exactly what I needed and it works as advertised, many thanks for it!

**Comment by gh0st-work** [comment]
Ok, thanks for your feedback. Will be fixed in a couple of days.

**Comment by gh0st-work** [comment]
Added in [v1.4.5](https://github.com/gh0st-work/solid-js-router/releases/tag/1.4.5)
